/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectClubRouteImport } from './routes/select-club'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CashRouteImport } from './routes/cash'
import { Route as IndexRouteImport } from './routes/index'

const SelectClubRoute = SelectClubRouteImport.update({
  id: '/select-club',
  path: '/select-club',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/expenses': typeof ExpensesRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/select-club': typeof SelectClubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/expenses': typeof ExpensesRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/select-club': typeof SelectClubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/expenses': typeof ExpensesRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/select-club': typeof SelectClubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash'
    | '/expenses'
    | '/games'
    | '/login'
    | '/players'
    | '/select-club'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash'
    | '/expenses'
    | '/games'
    | '/login'
    | '/players'
    | '/select-club'
  id:
    | '__root__'
    | '/'
    | '/cash'
    | '/expenses'
    | '/games'
    | '/login'
    | '/players'
    | '/select-club'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  ExpensesRoute: typeof ExpensesRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  PlayersRoute: typeof PlayersRoute
  SelectClubRoute: typeof SelectClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-club': {
      id: '/select-club'
      path: '/select-club'
      fullPath: '/select-club'
      preLoaderRoute: typeof SelectClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  ExpensesRoute: ExpensesRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  PlayersRoute: PlayersRoute,
  SelectClubRoute: SelectClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
